# Generated by Django 3.2.5 on 2021-07-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
                ('disc', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
