# Generated by Django 3.2.5 on 2021-07-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
